### ISSUE TITLE
[Idea/Request] Differentiate Art/Story/Music uploads

### ISSUE THREAD

**Issue by PolarisBeaver** [CopperBadger/fastyle#81]
I've made a mockup of an idea for differentiating the types of uploads in "Browse" mode, and the home page, adding FA's default music and story icon overlays to the bottom right of the preview, so people know what type of submission it is.

![untitled](https://cloud.githubusercontent.com/assets/10394552/6117405/2db2a3e0-b069-11e4-8d07-ddfaec36a24f.png)

**Comment by rubi-t8** [comment]
To keep with the theme of the whole extension, we could actually put a
music or book icon in the corner. Would actually be kinda nice.

**Comment by CopperBadger** [comment]
I like this idea! Definitely, a glyphicon would be great for that. We'll want to make sure that it has a darkened background like the title so it'll stand out against the thumb, but we probably don't have to worry about hiding it on mouse-over since thumbs for writing / audio aren't exactly high-demand content. That aside, tucking the icon into the existing title heading would be the easiest solution; getting it to stick responsively to the bottom of the container can be a pain.

Now, if only we could make the thumbnails not compressed / undersized to oblivion T_T

**Comment by rubi-t8** [comment]
We could make our own images for audio and story submissions that don't
have an image. And adding a translucent black background to the corner
glyph would make it work with lighter backgrounds.

**Comment by CopperBadger** [comment]
My pal Rechner recommended that we make our own default images for them (or, more likely, have someone make them for us, probably the same person who does the logo). Agreed on translucent black background for glyph, and if you do get it in the corner could you make it a neat little circle? Adding the `img-circle` class should do the trick for that.

**Comment by rubi-t8** [comment]
Done! I also added `submission-image`, `submission-text`, or `submission-music` to each thumbnail if we want to do any sort of styling or otherwise to different types of submissions.
